id = "go-zero-api-dsl"
name = "Go Zero API DSL"
version = "0.0.1"
schema_version = 1
authors = ["hey"]
description = "Syntax highlighting for go-zero API DSL files in Zed."
repository = "https://github.com/bughey/go-zero-api-dsl"

[grammars.go_zero_api]
repository = "https://github.com/bughey/go-zero-api-dsl"
rev = "025e977855708be1b71398045f915beffcaf519b"
path = "tree-sitter-go-zero-api"
