id = "go-zero-api-dsl"
name = "Go Zero API DSL"
version = "0.0.1"
schema_version = 1
authors = ["hey"]
description = "Syntax highlighting for go-zero API DSL files in Zed."
repository = "https://github.com/bughey/go-zero-api-dsl"

[grammars.go_zero_api]
repository = "file:///Users/hey/dev/code/go/gozero/code/zed-go-zero-api-dsl"
rev = "e1c645cae85f97a885da406e35ce5c97589cc6f1"
path = "tree-sitter-go-zero-api"
