/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 87
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 61
#define ALIAS_COUNT 1
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 10
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 16
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_syntax = 2,
  anon_sym_EQ = 3,
  anon_sym_info = 4,
  anon_sym_LPAREN = 5,
  anon_sym_RPAREN = 6,
  anon_sym_COLON = 7,
  anon_sym_import = 8,
  anon_sym_type = 9,
  anon_sym_LBRACE = 10,
  anon_sym_RBRACE = 11,
  anon_sym_service = 12,
  anon_sym_ATserver = 13,
  anon_sym_AThandler = 14,
  anon_sym_returns = 15,
  anon_sym_SLASH = 16,
  anon_sym_get = 17,
  anon_sym_post = 18,
  anon_sym_put = 19,
  anon_sym_patch = 20,
  anon_sym_delete = 21,
  anon_sym_head = 22,
  sym_service_identifier = 23,
  sym_field_type = 24,
  sym_path_segment = 25,
  sym_path_parameter = 26,
  sym_literal_value = 27,
  anon_sym_DQUOTE = 28,
  aux_sym_string_token1 = 29,
  sym_escape_sequence = 30,
  sym_struct_tag = 31,
  sym_comment = 32,
  sym_source_file = 33,
  sym__statement = 34,
  sym_syntax_declaration = 35,
  sym_info_block = 36,
  sym_key_value_property = 37,
  sym_import_declaration = 38,
  sym_import_block = 39,
  sym_type_declaration = 40,
  sym_type_group = 41,
  sym_type_spec = 42,
  sym_field_declaration = 43,
  sym_service_block = 44,
  sym_server_annotation = 45,
  sym_handler_annotation = 46,
  sym_route_declaration = 47,
  sym_type_reference = 48,
  sym_returns_clause = 49,
  sym_route_path = 50,
  sym_http_method = 51,
  sym_string = 52,
  aux_sym_source_file_repeat1 = 53,
  aux_sym_info_block_repeat1 = 54,
  aux_sym_import_block_repeat1 = 55,
  aux_sym_type_group_repeat1 = 56,
  aux_sym_type_spec_repeat1 = 57,
  aux_sym_service_block_repeat1 = 58,
  aux_sym_route_path_repeat1 = 59,
  aux_sym_string_repeat1 = 60,
  alias_sym_type_identifier = 61,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_syntax] = "syntax",
  [anon_sym_EQ] = "=",
  [anon_sym_info] = "info",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_import] = "import",
  [anon_sym_type] = "type",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_service] = "service",
  [anon_sym_ATserver] = "@server",
  [anon_sym_AThandler] = "@handler",
  [anon_sym_returns] = "returns",
  [anon_sym_SLASH] = "/",
  [anon_sym_get] = "get",
  [anon_sym_post] = "post",
  [anon_sym_put] = "put",
  [anon_sym_patch] = "patch",
  [anon_sym_delete] = "delete",
  [anon_sym_head] = "head",
  [sym_service_identifier] = "service_identifier",
  [sym_field_type] = "field_type",
  [sym_path_segment] = "path_segment",
  [sym_path_parameter] = "path_parameter",
  [sym_literal_value] = "literal_value",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_escape_sequence] = "escape_sequence",
  [sym_struct_tag] = "struct_tag",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_syntax_declaration] = "syntax_declaration",
  [sym_info_block] = "info_block",
  [sym_key_value_property] = "key_value_property",
  [sym_import_declaration] = "import_declaration",
  [sym_import_block] = "import_block",
  [sym_type_declaration] = "type_declaration",
  [sym_type_group] = "type_group",
  [sym_type_spec] = "type_spec",
  [sym_field_declaration] = "field_declaration",
  [sym_service_block] = "service_block",
  [sym_server_annotation] = "server_annotation",
  [sym_handler_annotation] = "handler_annotation",
  [sym_route_declaration] = "route_declaration",
  [sym_type_reference] = "type_reference",
  [sym_returns_clause] = "returns_clause",
  [sym_route_path] = "route_path",
  [sym_http_method] = "http_method",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_info_block_repeat1] = "info_block_repeat1",
  [aux_sym_import_block_repeat1] = "import_block_repeat1",
  [aux_sym_type_group_repeat1] = "type_group_repeat1",
  [aux_sym_type_spec_repeat1] = "type_spec_repeat1",
  [aux_sym_service_block_repeat1] = "service_block_repeat1",
  [aux_sym_route_path_repeat1] = "route_path_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [alias_sym_type_identifier] = "type_identifier",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_syntax] = anon_sym_syntax,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_info] = anon_sym_info,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_service] = anon_sym_service,
  [anon_sym_ATserver] = anon_sym_ATserver,
  [anon_sym_AThandler] = anon_sym_AThandler,
  [anon_sym_returns] = anon_sym_returns,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_get] = anon_sym_get,
  [anon_sym_post] = anon_sym_post,
  [anon_sym_put] = anon_sym_put,
  [anon_sym_patch] = anon_sym_patch,
  [anon_sym_delete] = anon_sym_delete,
  [anon_sym_head] = anon_sym_head,
  [sym_service_identifier] = sym_service_identifier,
  [sym_field_type] = sym_field_type,
  [sym_path_segment] = sym_path_segment,
  [sym_path_parameter] = sym_path_parameter,
  [sym_literal_value] = sym_literal_value,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_struct_tag] = sym_struct_tag,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_syntax_declaration] = sym_syntax_declaration,
  [sym_info_block] = sym_info_block,
  [sym_key_value_property] = sym_key_value_property,
  [sym_import_declaration] = sym_import_declaration,
  [sym_import_block] = sym_import_block,
  [sym_type_declaration] = sym_type_declaration,
  [sym_type_group] = sym_type_group,
  [sym_type_spec] = sym_type_spec,
  [sym_field_declaration] = sym_field_declaration,
  [sym_service_block] = sym_service_block,
  [sym_server_annotation] = sym_server_annotation,
  [sym_handler_annotation] = sym_handler_annotation,
  [sym_route_declaration] = sym_route_declaration,
  [sym_type_reference] = sym_type_reference,
  [sym_returns_clause] = sym_returns_clause,
  [sym_route_path] = sym_route_path,
  [sym_http_method] = sym_http_method,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_info_block_repeat1] = aux_sym_info_block_repeat1,
  [aux_sym_import_block_repeat1] = aux_sym_import_block_repeat1,
  [aux_sym_type_group_repeat1] = aux_sym_type_group_repeat1,
  [aux_sym_type_spec_repeat1] = aux_sym_type_spec_repeat1,
  [aux_sym_service_block_repeat1] = aux_sym_service_block_repeat1,
  [aux_sym_route_path_repeat1] = aux_sym_route_path_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [alias_sym_type_identifier] = alias_sym_type_identifier,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_syntax] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_info] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_service] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATserver] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AThandler] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_returns] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_get] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_post] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_put] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_patch] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_delete] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_head] = {
    .visible = true,
    .named = false,
  },
  [sym_service_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_field_type] = {
    .visible = true,
    .named = true,
  },
  [sym_path_segment] = {
    .visible = true,
    .named = true,
  },
  [sym_path_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_literal_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_syntax_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_info_block] = {
    .visible = true,
    .named = true,
  },
  [sym_key_value_property] = {
    .visible = true,
    .named = true,
  },
  [sym_import_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_import_block] = {
    .visible = true,
    .named = true,
  },
  [sym_type_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_type_group] = {
    .visible = true,
    .named = true,
  },
  [sym_type_spec] = {
    .visible = true,
    .named = true,
  },
  [sym_field_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_service_block] = {
    .visible = true,
    .named = true,
  },
  [sym_server_annotation] = {
    .visible = true,
    .named = true,
  },
  [sym_handler_annotation] = {
    .visible = true,
    .named = true,
  },
  [sym_route_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_type_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_returns_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_route_path] = {
    .visible = true,
    .named = true,
  },
  [sym_http_method] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_info_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_import_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_group_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_spec_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_service_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_route_path_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_type_identifier] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_method = 2,
  field_name = 3,
  field_path = 4,
  field_request = 5,
  field_response = 6,
  field_tag = 7,
  field_type = 8,
  field_value = 9,
  field_version = 10,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_method] = "method",
  [field_name] = "name",
  [field_path] = "path",
  [field_request] = "request",
  [field_response] = "response",
  [field_tag] = "tag",
  [field_type] = "type",
  [field_value] = "value",
  [field_version] = "version",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 1},
  [7] = {.index = 7, .length = 1},
  [8] = {.index = 8, .length = 2},
  [9] = {.index = 10, .length = 2},
  [10] = {.index = 12, .length = 2},
  [11] = {.index = 14, .length = 3},
  [12] = {.index = 17, .length = 3},
  [13] = {.index = 20, .length = 3},
  [14] = {.index = 23, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_path, 1},
  [1] =
    {field_version, 2},
  [2] =
    {field_path, 0},
  [3] =
    {field_path, 1, .inherited = true},
  [4] =
    {field_path, 0, .inherited = true},
    {field_path, 1, .inherited = true},
  [6] =
    {field_name, 0},
  [7] =
    {field_name, 1},
  [8] =
    {field_key, 0},
    {field_value, 2},
  [10] =
    {field_name, 0},
    {field_type, 1},
  [12] =
    {field_method, 0},
    {field_path, 1},
  [14] =
    {field_name, 0},
    {field_tag, 2},
    {field_type, 1},
  [17] =
    {field_method, 0},
    {field_path, 1},
    {field_request, 2},
  [20] =
    {field_method, 0},
    {field_path, 1},
    {field_response, 2},
  [23] =
    {field_method, 0},
    {field_path, 1},
    {field_request, 2},
    {field_response, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [6] = {
    [0] = alias_sym_type_identifier,
  },
  [15] = {
    [1] = alias_sym_type_identifier,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 38,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 52,
  [58] = 48,
  [59] = 51,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 23,
  [68] = 27,
  [69] = 69,
  [70] = 31,
  [71] = 71,
  [72] = 22,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 75,
};

static const TSCharacterRange sym_path_segment_character_set_1[] = {
  {'!', '!'}, {'$', '.'}, {'0', '9'}, {';', ';'}, {'=', '='}, {'@', 'Z'}, {'_', '_'}, {'a', 'z'},
  {'~', '~'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(52);
      ADVANCE_MAP(
        '"', 152,
        '(', 54,
        ')', 56,
        '/', 67,
        ':', 57,
        '=', 53,
        '@', 27,
        '\\', 47,
        '`', 11,
        'd', 90,
        'g', 91,
        'h', 92,
        'p', 87,
        'r', 94,
        '{', 58,
        '}', 59,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(50);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '"') ADVANCE(152);
      if (lookahead == '/') ADVANCE(154);
      if (lookahead == '\\') ADVANCE(47);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(153);
      if (lookahead != 0) ADVANCE(156);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(152);
      if (lookahead == '/') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(152);
      if (lookahead == '/') ADVANCE(149);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (lookahead != 0 &&
          lookahead != ')' &&
          lookahead != '`') ADVANCE(151);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '(', 54,
        '/', 67,
        '@', 27,
        'd', 23,
        'g', 19,
        'h', 21,
        'p', 14,
        'r', 25,
        '}', 59,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        '(', 54,
        '/', 8,
        '@', 27,
        'd', 23,
        'g', 19,
        'h', 21,
        'p', 14,
        'r', 25,
        '}', 59,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        '(', 55,
        '/', 67,
        ':', 48,
        '@', 127,
        'd', 118,
        'g', 119,
        'h', 122,
        'p', 114,
        'r', 124,
        '}', 59,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= ';') ||
          lookahead == '=' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '~') ADVANCE(147);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(49);
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == '[') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(159);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 10:
      if (lookahead == ']') ADVANCE(49);
      END_STATE();
    case 11:
      if (lookahead == '`') ADVANCE(158);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(11);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(31);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(17);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(40);
      if (lookahead == 'o') ADVANCE(38);
      if (lookahead == 'u') ADVANCE(41);
      END_STATE();
    case 15:
      if (lookahead == 'c') ADVANCE(28);
      END_STATE();
    case 16:
      if (lookahead == 'd') ADVANCE(30);
      END_STATE();
    case 17:
      if (lookahead == 'd') ADVANCE(83);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(80);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(44);
      END_STATE();
    case 27:
      if (lookahead == 'h') ADVANCE(12);
      if (lookahead == 's') ADVANCE(18);
      END_STATE();
    case 28:
      if (lookahead == 'h') ADVANCE(77);
      END_STATE();
    case 29:
      if (lookahead == 'l') ADVANCE(26);
      END_STATE();
    case 30:
      if (lookahead == 'l') ADVANCE(24);
      END_STATE();
    case 31:
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 32:
      if (lookahead == 'n') ADVANCE(37);
      END_STATE();
    case 33:
      if (lookahead == 'r') ADVANCE(46);
      END_STATE();
    case 34:
      if (lookahead == 'r') ADVANCE(60);
      END_STATE();
    case 35:
      if (lookahead == 'r') ADVANCE(62);
      END_STATE();
    case 36:
      if (lookahead == 'r') ADVANCE(32);
      END_STATE();
    case 37:
      if (lookahead == 's') ADVANCE(64);
      END_STATE();
    case 38:
      if (lookahead == 's') ADVANCE(43);
      END_STATE();
    case 39:
      if (lookahead == 't') ADVANCE(68);
      END_STATE();
    case 40:
      if (lookahead == 't') ADVANCE(15);
      END_STATE();
    case 41:
      if (lookahead == 't') ADVANCE(74);
      END_STATE();
    case 42:
      if (lookahead == 't') ADVANCE(45);
      END_STATE();
    case 43:
      if (lookahead == 't') ADVANCE(71);
      END_STATE();
    case 44:
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 45:
      if (lookahead == 'u') ADVANCE(36);
      END_STATE();
    case 46:
      if (lookahead == 'v') ADVANCE(22);
      END_STATE();
    case 47:
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(157);
      END_STATE();
    case 48:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 49:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 50:
      if (eof) ADVANCE(52);
      ADVANCE_MAP(
        '"', 152,
        '(', 54,
        ')', 56,
        '/', 67,
        ':', 57,
        '=', 53,
        '@', 27,
        '`', 11,
        'd', 90,
        'g', 91,
        'h', 92,
        'p', 87,
        'r', 94,
        '{', 58,
        '}', 59,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(50);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 51:
      if (eof) ADVANCE(52);
      if (lookahead == '"') ADVANCE(152);
      if (lookahead == '(') ADVANCE(54);
      if (lookahead == ')') ADVANCE(56);
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == '`') ADVANCE(11);
      if (lookahead == '}') ADVANCE(59);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(51);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_ATserver);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_ATserver);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_AThandler);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_AThandler);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_returns);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_returns);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_returns);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(159);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_get);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_get);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_get);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_post);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_post);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_post);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_put);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_put);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_put);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_patch);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_patch);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_patch);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_delete);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_delete);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_delete);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_head);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_head);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_head);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(89);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(103);
      if (lookahead == 'o') ADVANCE(101);
      if (lookahead == 'u') ADVANCE(104);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(96);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(84);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(97);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(102);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(105);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(107);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(95);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(100);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(98);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(106);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(108);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(93);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(99);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_service_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_field_type);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'a') ADVANCE(132);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'a') ADVANCE(116);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'a') ADVANCE(140);
      if (lookahead == 'o') ADVANCE(138);
      if (lookahead == 'u') ADVANCE(141);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'c') ADVANCE(128);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'd') ADVANCE(85);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'd') ADVANCE(129);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'e') ADVANCE(130);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'e') ADVANCE(139);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'e') ADVANCE(133);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'e') ADVANCE(82);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'e') ADVANCE(113);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'e') ADVANCE(134);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'e') ADVANCE(142);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'e') ADVANCE(135);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'e') ADVANCE(144);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'h') ADVANCE(112);
      if (lookahead == 's') ADVANCE(120);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'h') ADVANCE(79);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'l') ADVANCE(125);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'l') ADVANCE(126);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'n') ADVANCE(137);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'n') ADVANCE(117);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'r') ADVANCE(146);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'r') ADVANCE(61);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'r') ADVANCE(63);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'r') ADVANCE(131);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 's') ADVANCE(66);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 's') ADVANCE(143);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 't') ADVANCE(70);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 't') ADVANCE(115);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 't') ADVANCE(76);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 't') ADVANCE(145);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 't') ADVANCE(73);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 't') ADVANCE(121);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'u') ADVANCE(136);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_path_segment);
      if (lookahead == 'v') ADVANCE(123);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_path_segment);
      if (set_contains(sym_path_segment_character_set_1, 9, lookahead)) ADVANCE(147);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_path_parameter);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_literal_value);
      if (lookahead == '/') ADVANCE(150);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != ')' &&
          lookahead != '`') ADVANCE(151);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_literal_value);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == ')' ||
          lookahead == '`') ADVANCE(159);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(150);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_literal_value);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != ')' &&
          lookahead != '`') ADVANCE(151);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(154);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(153);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(156);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(155);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(156);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(159);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(155);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(156);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(sym_struct_tag);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(159);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'i') ADVANCE(1);
      if (lookahead == 's') ADVANCE(2);
      if (lookahead == 't') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'm') ADVANCE(4);
      if (lookahead == 'n') ADVANCE(5);
      END_STATE();
    case 2:
      if (lookahead == 'e') ADVANCE(6);
      if (lookahead == 'y') ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == 'y') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == 'p') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == 'f') ADVANCE(10);
      END_STATE();
    case 6:
      if (lookahead == 'r') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 8:
      if (lookahead == 'p') ADVANCE(13);
      END_STATE();
    case 9:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 11:
      if (lookahead == 'v') ADVANCE(16);
      END_STATE();
    case 12:
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 14:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_info);
      END_STATE();
    case 16:
      if (lookahead == 'i') ADVANCE(20);
      END_STATE();
    case 17:
      if (lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 19:
      if (lookahead == 't') ADVANCE(22);
      END_STATE();
    case 20:
      if (lookahead == 'c') ADVANCE(23);
      END_STATE();
    case 21:
      if (lookahead == 'x') ADVANCE(24);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_syntax);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_service);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 51},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 5},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 5},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 51},
  [10] = {.lex_state = 51},
  [11] = {.lex_state = 5},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 5},
  [14] = {.lex_state = 5},
  [15] = {.lex_state = 5},
  [16] = {.lex_state = 5},
  [17] = {.lex_state = 5},
  [18] = {.lex_state = 5},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 5},
  [21] = {.lex_state = 5},
  [22] = {.lex_state = 51},
  [23] = {.lex_state = 51},
  [24] = {.lex_state = 51},
  [25] = {.lex_state = 51},
  [26] = {.lex_state = 51},
  [27] = {.lex_state = 51},
  [28] = {.lex_state = 51},
  [29] = {.lex_state = 51},
  [30] = {.lex_state = 51},
  [31] = {.lex_state = 51},
  [32] = {.lex_state = 51},
  [33] = {.lex_state = 51},
  [34] = {.lex_state = 51},
  [35] = {.lex_state = 51},
  [36] = {.lex_state = 51},
  [37] = {.lex_state = 51},
  [38] = {.lex_state = 51},
  [39] = {.lex_state = 51},
  [40] = {.lex_state = 51},
  [41] = {.lex_state = 51},
  [42] = {.lex_state = 51},
  [43] = {.lex_state = 51},
  [44] = {.lex_state = 51},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 51},
  [47] = {.lex_state = 51},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 51},
  [51] = {.lex_state = 51},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 51},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 51},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 51},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 51},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 51},
  [65] = {.lex_state = 51},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 51},
  [68] = {.lex_state = 51},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 51},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 51},
  [73] = {.lex_state = 51},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 51},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 7},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 9},
  [86] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_syntax] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_info] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_service] = ACTIONS(1),
    [anon_sym_ATserver] = ACTIONS(1),
    [anon_sym_AThandler] = ACTIONS(1),
    [anon_sym_returns] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_get] = ACTIONS(1),
    [anon_sym_post] = ACTIONS(1),
    [anon_sym_put] = ACTIONS(1),
    [anon_sym_patch] = ACTIONS(1),
    [anon_sym_delete] = ACTIONS(1),
    [anon_sym_head] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_struct_tag] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(76),
    [sym__statement] = STATE(9),
    [sym_syntax_declaration] = STATE(9),
    [sym_info_block] = STATE(9),
    [sym_import_declaration] = STATE(9),
    [sym_type_declaration] = STATE(9),
    [sym_service_block] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_syntax] = ACTIONS(7),
    [anon_sym_info] = ACTIONS(9),
    [anon_sym_import] = ACTIONS(11),
    [anon_sym_type] = ACTIONS(13),
    [anon_sym_service] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_RBRACE,
    ACTIONS(21), 1,
      sym_path_segment,
    ACTIONS(23), 1,
      sym_path_parameter,
    STATE(3), 1,
      aux_sym_route_path_repeat1,
    ACTIONS(17), 10,
      anon_sym_LPAREN,
      anon_sym_ATserver,
      anon_sym_AThandler,
      anon_sym_returns,
      anon_sym_get,
      anon_sym_post,
      anon_sym_put,
      anon_sym_patch,
      anon_sym_delete,
      anon_sym_head,
  [28] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_RBRACE,
    ACTIONS(29), 1,
      sym_path_segment,
    ACTIONS(32), 1,
      sym_path_parameter,
    STATE(3), 1,
      aux_sym_route_path_repeat1,
    ACTIONS(25), 10,
      anon_sym_LPAREN,
      anon_sym_ATserver,
      anon_sym_AThandler,
      anon_sym_returns,
      anon_sym_get,
      anon_sym_post,
      anon_sym_put,
      anon_sym_patch,
      anon_sym_delete,
      anon_sym_head,
  [56] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_RBRACE,
    ACTIONS(37), 1,
      anon_sym_ATserver,
    ACTIONS(39), 1,
      anon_sym_AThandler,
    STATE(63), 1,
      sym_http_method,
    STATE(5), 4,
      sym_server_annotation,
      sym_handler_annotation,
      sym_route_declaration,
      aux_sym_service_block_repeat1,
    ACTIONS(41), 6,
      anon_sym_get,
      anon_sym_post,
      anon_sym_put,
      anon_sym_patch,
      anon_sym_delete,
      anon_sym_head,
  [86] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_ATserver,
    ACTIONS(39), 1,
      anon_sym_AThandler,
    ACTIONS(43), 1,
      anon_sym_RBRACE,
    STATE(63), 1,
      sym_http_method,
    STATE(7), 4,
      sym_server_annotation,
      sym_handler_annotation,
      sym_route_declaration,
      aux_sym_service_block_repeat1,
    ACTIONS(41), 6,
      anon_sym_get,
      anon_sym_post,
      anon_sym_put,
      anon_sym_patch,
      anon_sym_delete,
      anon_sym_head,
  [116] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      sym_path_segment,
    ACTIONS(23), 1,
      sym_path_parameter,
    ACTIONS(47), 1,
      anon_sym_RBRACE,
    STATE(2), 1,
      aux_sym_route_path_repeat1,
    ACTIONS(45), 10,
      anon_sym_LPAREN,
      anon_sym_ATserver,
      anon_sym_AThandler,
      anon_sym_returns,
      anon_sym_get,
      anon_sym_post,
      anon_sym_put,
      anon_sym_patch,
      anon_sym_delete,
      anon_sym_head,
  [144] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    ACTIONS(51), 1,
      anon_sym_ATserver,
    ACTIONS(54), 1,
      anon_sym_AThandler,
    STATE(63), 1,
      sym_http_method,
    STATE(7), 4,
      sym_server_annotation,
      sym_handler_annotation,
      sym_route_declaration,
      aux_sym_service_block_repeat1,
    ACTIONS(57), 6,
      anon_sym_get,
      anon_sym_post,
      anon_sym_put,
      anon_sym_patch,
      anon_sym_delete,
      anon_sym_head,
  [174] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 1,
      anon_sym_SLASH,
    ACTIONS(62), 2,
      anon_sym_RBRACE,
      sym_path_parameter,
    ACTIONS(60), 11,
      anon_sym_LPAREN,
      anon_sym_ATserver,
      anon_sym_AThandler,
      anon_sym_returns,
      anon_sym_get,
      anon_sym_post,
      anon_sym_put,
      anon_sym_patch,
      anon_sym_delete,
      anon_sym_head,
      sym_path_segment,
  [198] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_syntax,
    ACTIONS(9), 1,
      anon_sym_info,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(13), 1,
      anon_sym_type,
    ACTIONS(15), 1,
      anon_sym_service,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
    STATE(10), 7,
      sym__statement,
      sym_syntax_declaration,
      sym_info_block,
      sym_import_declaration,
      sym_type_declaration,
      sym_service_block,
      aux_sym_source_file_repeat1,
  [229] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
    ACTIONS(70), 1,
      anon_sym_syntax,
    ACTIONS(73), 1,
      anon_sym_info,
    ACTIONS(76), 1,
      anon_sym_import,
    ACTIONS(79), 1,
      anon_sym_type,
    ACTIONS(82), 1,
      anon_sym_service,
    STATE(10), 7,
      sym__statement,
      sym_syntax_declaration,
      sym_info_block,
      sym_import_declaration,
      sym_type_declaration,
      sym_service_block,
      aux_sym_source_file_repeat1,
  [260] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_LPAREN,
    ACTIONS(89), 1,
      anon_sym_returns,
    STATE(13), 1,
      sym_type_reference,
    STATE(21), 1,
      sym_returns_clause,
    ACTIONS(87), 9,
      anon_sym_RBRACE,
      anon_sym_ATserver,
      anon_sym_AThandler,
      anon_sym_get,
      anon_sym_post,
      anon_sym_put,
      anon_sym_patch,
      anon_sym_delete,
      anon_sym_head,
  [287] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 2,
      anon_sym_RBRACE,
      sym_path_parameter,
    ACTIONS(25), 11,
      anon_sym_LPAREN,
      anon_sym_ATserver,
      anon_sym_AThandler,
      anon_sym_returns,
      anon_sym_get,
      anon_sym_post,
      anon_sym_put,
      anon_sym_patch,
      anon_sym_delete,
      anon_sym_head,
      sym_path_segment,
  [308] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      anon_sym_returns,
    STATE(19), 1,
      sym_returns_clause,
    ACTIONS(91), 9,
      anon_sym_RBRACE,
      anon_sym_ATserver,
      anon_sym_AThandler,
      anon_sym_get,
      anon_sym_post,
      anon_sym_put,
      anon_sym_patch,
      anon_sym_delete,
      anon_sym_head,
  [329] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 10,
      anon_sym_RBRACE,
      anon_sym_ATserver,
      anon_sym_AThandler,
      anon_sym_returns,
      anon_sym_get,
      anon_sym_post,
      anon_sym_put,
      anon_sym_patch,
      anon_sym_delete,
      anon_sym_head,
  [345] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 10,
      anon_sym_RBRACE,
      anon_sym_ATserver,
      anon_sym_AThandler,
      anon_sym_returns,
      anon_sym_get,
      anon_sym_post,
      anon_sym_put,
      anon_sym_patch,
      anon_sym_delete,
      anon_sym_head,
  [361] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 9,
      anon_sym_RBRACE,
      anon_sym_ATserver,
      anon_sym_AThandler,
      anon_sym_get,
      anon_sym_post,
      anon_sym_put,
      anon_sym_patch,
      anon_sym_delete,
      anon_sym_head,
  [376] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 9,
      anon_sym_RBRACE,
      anon_sym_ATserver,
      anon_sym_AThandler,
      anon_sym_get,
      anon_sym_post,
      anon_sym_put,
      anon_sym_patch,
      anon_sym_delete,
      anon_sym_head,
  [391] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 9,
      anon_sym_RBRACE,
      anon_sym_ATserver,
      anon_sym_AThandler,
      anon_sym_get,
      anon_sym_post,
      anon_sym_put,
      anon_sym_patch,
      anon_sym_delete,
      anon_sym_head,
  [406] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 9,
      anon_sym_RBRACE,
      anon_sym_ATserver,
      anon_sym_AThandler,
      anon_sym_get,
      anon_sym_post,
      anon_sym_put,
      anon_sym_patch,
      anon_sym_delete,
      anon_sym_head,
  [421] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 9,
      anon_sym_RBRACE,
      anon_sym_ATserver,
      anon_sym_AThandler,
      anon_sym_get,
      anon_sym_post,
      anon_sym_put,
      anon_sym_patch,
      anon_sym_delete,
      anon_sym_head,
  [436] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 9,
      anon_sym_RBRACE,
      anon_sym_ATserver,
      anon_sym_AThandler,
      anon_sym_get,
      anon_sym_post,
      anon_sym_put,
      anon_sym_patch,
      anon_sym_delete,
      anon_sym_head,
  [451] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 8,
      ts_builtin_sym_end,
      anon_sym_syntax,
      anon_sym_info,
      anon_sym_RPAREN,
      anon_sym_import,
      anon_sym_type,
      anon_sym_service,
      anon_sym_DQUOTE,
  [465] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 8,
      ts_builtin_sym_end,
      anon_sym_syntax,
      anon_sym_info,
      anon_sym_RPAREN,
      anon_sym_import,
      anon_sym_type,
      anon_sym_service,
      anon_sym_DQUOTE,
  [479] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 6,
      ts_builtin_sym_end,
      anon_sym_syntax,
      anon_sym_info,
      anon_sym_import,
      anon_sym_type,
      anon_sym_service,
  [491] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 6,
      ts_builtin_sym_end,
      anon_sym_syntax,
      anon_sym_info,
      anon_sym_import,
      anon_sym_type,
      anon_sym_service,
  [503] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 6,
      ts_builtin_sym_end,
      anon_sym_syntax,
      anon_sym_info,
      anon_sym_import,
      anon_sym_type,
      anon_sym_service,
  [515] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 6,
      ts_builtin_sym_end,
      anon_sym_syntax,
      anon_sym_info,
      anon_sym_import,
      anon_sym_type,
      anon_sym_service,
  [527] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 6,
      ts_builtin_sym_end,
      anon_sym_syntax,
      anon_sym_info,
      anon_sym_import,
      anon_sym_type,
      anon_sym_service,
  [539] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 6,
      ts_builtin_sym_end,
      anon_sym_syntax,
      anon_sym_info,
      anon_sym_import,
      anon_sym_type,
      anon_sym_service,
  [551] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 6,
      ts_builtin_sym_end,
      anon_sym_syntax,
      anon_sym_info,
      anon_sym_import,
      anon_sym_type,
      anon_sym_service,
  [563] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 6,
      ts_builtin_sym_end,
      anon_sym_syntax,
      anon_sym_info,
      anon_sym_import,
      anon_sym_type,
      anon_sym_service,
  [575] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 6,
      ts_builtin_sym_end,
      anon_sym_syntax,
      anon_sym_info,
      anon_sym_import,
      anon_sym_type,
      anon_sym_service,
  [587] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 6,
      ts_builtin_sym_end,
      anon_sym_syntax,
      anon_sym_info,
      anon_sym_import,
      anon_sym_type,
      anon_sym_service,
  [599] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 6,
      ts_builtin_sym_end,
      anon_sym_syntax,
      anon_sym_info,
      anon_sym_import,
      anon_sym_type,
      anon_sym_service,
  [611] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 6,
      ts_builtin_sym_end,
      anon_sym_syntax,
      anon_sym_info,
      anon_sym_import,
      anon_sym_type,
      anon_sym_service,
  [623] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 6,
      ts_builtin_sym_end,
      anon_sym_syntax,
      anon_sym_info,
      anon_sym_import,
      anon_sym_type,
      anon_sym_service,
  [635] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 6,
      ts_builtin_sym_end,
      anon_sym_syntax,
      anon_sym_info,
      anon_sym_import,
      anon_sym_type,
      anon_sym_service,
  [647] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      sym_identifier,
    ACTIONS(143), 1,
      anon_sym_RBRACE,
    STATE(42), 2,
      sym_field_declaration,
      aux_sym_type_spec_repeat1,
  [661] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      sym_identifier,
    ACTIONS(145), 1,
      anon_sym_RBRACE,
    STATE(42), 2,
      sym_field_declaration,
      aux_sym_type_spec_repeat1,
  [675] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      sym_identifier,
    ACTIONS(150), 1,
      anon_sym_RPAREN,
    STATE(40), 2,
      sym_type_spec,
      aux_sym_type_group_repeat1,
  [689] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      sym_identifier,
    ACTIONS(154), 1,
      anon_sym_LPAREN,
    STATE(25), 2,
      sym_type_group,
      sym_type_spec,
  [703] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 1,
      sym_identifier,
    ACTIONS(159), 1,
      anon_sym_RBRACE,
    STATE(42), 2,
      sym_field_declaration,
      aux_sym_type_spec_repeat1,
  [717] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      sym_identifier,
    ACTIONS(163), 1,
      anon_sym_RPAREN,
    STATE(47), 2,
      sym_key_value_property,
      aux_sym_info_block_repeat1,
  [731] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      sym_identifier,
    ACTIONS(165), 1,
      anon_sym_RPAREN,
    STATE(53), 2,
      sym_key_value_property,
      aux_sym_info_block_repeat1,
  [745] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      anon_sym_RPAREN,
    ACTIONS(169), 1,
      anon_sym_DQUOTE,
    STATE(55), 1,
      aux_sym_import_block_repeat1,
    STATE(69), 1,
      sym_string,
  [761] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      sym_identifier,
    ACTIONS(171), 1,
      anon_sym_RPAREN,
    STATE(44), 2,
      sym_key_value_property,
      aux_sym_info_block_repeat1,
  [775] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      sym_identifier,
    ACTIONS(173), 1,
      anon_sym_RPAREN,
    STATE(53), 2,
      sym_key_value_property,
      aux_sym_info_block_repeat1,
  [789] = 5,
    ACTIONS(175), 1,
      anon_sym_DQUOTE,
    ACTIONS(177), 1,
      aux_sym_string_token1,
    ACTIONS(179), 1,
      sym_escape_sequence,
    ACTIONS(181), 1,
      sym_comment,
    STATE(60), 1,
      aux_sym_string_repeat1,
  [805] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      anon_sym_DQUOTE,
    ACTIONS(183), 1,
      anon_sym_RPAREN,
    STATE(45), 1,
      aux_sym_import_block_repeat1,
    STATE(69), 1,
      sym_string,
  [821] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      sym_identifier,
    ACTIONS(187), 1,
      anon_sym_RPAREN,
    STATE(40), 2,
      sym_type_spec,
      aux_sym_type_group_repeat1,
  [835] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      sym_identifier,
    ACTIONS(189), 1,
      anon_sym_RBRACE,
    STATE(38), 2,
      sym_field_declaration,
      aux_sym_type_spec_repeat1,
  [849] = 5,
    ACTIONS(181), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_DQUOTE,
    ACTIONS(193), 1,
      aux_sym_string_token1,
    ACTIONS(195), 1,
      sym_escape_sequence,
    STATE(48), 1,
      aux_sym_string_repeat1,
  [865] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      sym_identifier,
    ACTIONS(200), 1,
      anon_sym_RPAREN,
    STATE(53), 2,
      sym_key_value_property,
      aux_sym_info_block_repeat1,
  [879] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      anon_sym_DQUOTE,
    ACTIONS(202), 1,
      anon_sym_LPAREN,
    STATE(28), 1,
      sym_import_block,
    STATE(36), 1,
      sym_string,
  [895] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      anon_sym_RPAREN,
    ACTIONS(206), 1,
      anon_sym_DQUOTE,
    STATE(55), 1,
      aux_sym_import_block_repeat1,
    STATE(69), 1,
      sym_string,
  [911] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      sym_identifier,
    ACTIONS(209), 1,
      anon_sym_RPAREN,
    STATE(50), 2,
      sym_type_spec,
      aux_sym_type_group_repeat1,
  [925] = 5,
    ACTIONS(181), 1,
      sym_comment,
    ACTIONS(211), 1,
      anon_sym_DQUOTE,
    ACTIONS(213), 1,
      aux_sym_string_token1,
    ACTIONS(215), 1,
      sym_escape_sequence,
    STATE(58), 1,
      aux_sym_string_repeat1,
  [941] = 5,
    ACTIONS(177), 1,
      aux_sym_string_token1,
    ACTIONS(179), 1,
      sym_escape_sequence,
    ACTIONS(181), 1,
      sym_comment,
    ACTIONS(217), 1,
      anon_sym_DQUOTE,
    STATE(60), 1,
      aux_sym_string_repeat1,
  [957] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      sym_identifier,
    ACTIONS(219), 1,
      anon_sym_RBRACE,
    STATE(39), 2,
      sym_field_declaration,
      aux_sym_type_spec_repeat1,
  [971] = 5,
    ACTIONS(181), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_DQUOTE,
    ACTIONS(223), 1,
      aux_sym_string_token1,
    ACTIONS(226), 1,
      sym_escape_sequence,
    STATE(60), 1,
      aux_sym_string_repeat1,
  [987] = 4,
    ACTIONS(181), 1,
      sym_comment,
    ACTIONS(229), 1,
      sym_literal_value,
    ACTIONS(231), 1,
      anon_sym_DQUOTE,
    STATE(65), 1,
      sym_string,
  [1000] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      sym_struct_tag,
    ACTIONS(233), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1011] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_SLASH,
    STATE(11), 1,
      sym_route_path,
  [1021] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      sym_identifier,
    ACTIONS(241), 1,
      anon_sym_RPAREN,
  [1031] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [1039] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_LPAREN,
    STATE(18), 1,
      sym_type_reference,
  [1049] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [1057] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [1065] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 2,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
  [1073] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [1081] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      anon_sym_DQUOTE,
    STATE(30), 1,
      sym_string,
  [1091] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [1099] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1107] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      anon_sym_SLASH,
  [1114] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      anon_sym_LBRACE,
  [1121] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      ts_builtin_sym_end,
  [1128] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 1,
      anon_sym_EQ,
  [1135] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      sym_identifier,
  [1142] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      anon_sym_LPAREN,
  [1149] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      sym_field_type,
  [1156] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      anon_sym_LBRACE,
  [1163] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      anon_sym_RPAREN,
  [1170] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_COLON,
  [1177] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_LPAREN,
  [1184] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      sym_service_identifier,
  [1191] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      anon_sym_LBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 28,
  [SMALL_STATE(4)] = 56,
  [SMALL_STATE(5)] = 86,
  [SMALL_STATE(6)] = 116,
  [SMALL_STATE(7)] = 144,
  [SMALL_STATE(8)] = 174,
  [SMALL_STATE(9)] = 198,
  [SMALL_STATE(10)] = 229,
  [SMALL_STATE(11)] = 260,
  [SMALL_STATE(12)] = 287,
  [SMALL_STATE(13)] = 308,
  [SMALL_STATE(14)] = 329,
  [SMALL_STATE(15)] = 345,
  [SMALL_STATE(16)] = 361,
  [SMALL_STATE(17)] = 376,
  [SMALL_STATE(18)] = 391,
  [SMALL_STATE(19)] = 406,
  [SMALL_STATE(20)] = 421,
  [SMALL_STATE(21)] = 436,
  [SMALL_STATE(22)] = 451,
  [SMALL_STATE(23)] = 465,
  [SMALL_STATE(24)] = 479,
  [SMALL_STATE(25)] = 491,
  [SMALL_STATE(26)] = 503,
  [SMALL_STATE(27)] = 515,
  [SMALL_STATE(28)] = 527,
  [SMALL_STATE(29)] = 539,
  [SMALL_STATE(30)] = 551,
  [SMALL_STATE(31)] = 563,
  [SMALL_STATE(32)] = 575,
  [SMALL_STATE(33)] = 587,
  [SMALL_STATE(34)] = 599,
  [SMALL_STATE(35)] = 611,
  [SMALL_STATE(36)] = 623,
  [SMALL_STATE(37)] = 635,
  [SMALL_STATE(38)] = 647,
  [SMALL_STATE(39)] = 661,
  [SMALL_STATE(40)] = 675,
  [SMALL_STATE(41)] = 689,
  [SMALL_STATE(42)] = 703,
  [SMALL_STATE(43)] = 717,
  [SMALL_STATE(44)] = 731,
  [SMALL_STATE(45)] = 745,
  [SMALL_STATE(46)] = 761,
  [SMALL_STATE(47)] = 775,
  [SMALL_STATE(48)] = 789,
  [SMALL_STATE(49)] = 805,
  [SMALL_STATE(50)] = 821,
  [SMALL_STATE(51)] = 835,
  [SMALL_STATE(52)] = 849,
  [SMALL_STATE(53)] = 865,
  [SMALL_STATE(54)] = 879,
  [SMALL_STATE(55)] = 895,
  [SMALL_STATE(56)] = 911,
  [SMALL_STATE(57)] = 925,
  [SMALL_STATE(58)] = 941,
  [SMALL_STATE(59)] = 957,
  [SMALL_STATE(60)] = 971,
  [SMALL_STATE(61)] = 987,
  [SMALL_STATE(62)] = 1000,
  [SMALL_STATE(63)] = 1011,
  [SMALL_STATE(64)] = 1021,
  [SMALL_STATE(65)] = 1031,
  [SMALL_STATE(66)] = 1039,
  [SMALL_STATE(67)] = 1049,
  [SMALL_STATE(68)] = 1057,
  [SMALL_STATE(69)] = 1065,
  [SMALL_STATE(70)] = 1073,
  [SMALL_STATE(71)] = 1081,
  [SMALL_STATE(72)] = 1091,
  [SMALL_STATE(73)] = 1099,
  [SMALL_STATE(74)] = 1107,
  [SMALL_STATE(75)] = 1114,
  [SMALL_STATE(76)] = 1121,
  [SMALL_STATE(77)] = 1128,
  [SMALL_STATE(78)] = 1135,
  [SMALL_STATE(79)] = 1142,
  [SMALL_STATE(80)] = 1149,
  [SMALL_STATE(81)] = 1156,
  [SMALL_STATE(82)] = 1163,
  [SMALL_STATE(83)] = 1170,
  [SMALL_STATE(84)] = 1177,
  [SMALL_STATE(85)] = 1184,
  [SMALL_STATE(86)] = 1191,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_route_path, 2, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_route_path, 2, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_route_path_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_route_path_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_route_path_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_route_path_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_route_path, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_route_path, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_service_block_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_service_block_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_service_block_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_service_block_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_route_path_repeat1, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_route_path_repeat1, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_route_declaration, 2, 0, 10),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_route_declaration, 3, 0, 12),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_reference, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_reference, 3, 0, 15),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_handler_annotation, 2, 0, 7),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_server_annotation, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_returns_clause, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_route_declaration, 4, 0, 14),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_server_annotation, 4, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_route_declaration, 3, 0, 13),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_block, 3, 0, 4),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_declaration, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_info_block, 4, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_spec, 3, 0, 6),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_declaration, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_service_block, 4, 0, 7),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_syntax_declaration, 3, 0, 2),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_spec, 4, 0, 6),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_group, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_info_block, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_group, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_block, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_declaration, 2, 0, 1),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_service_block, 5, 0, 7),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [147] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_group_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_group_repeat1, 2, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_spec_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_spec_repeat1, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [197] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_info_block_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_info_block_repeat1, 2, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_import_block_repeat1, 2, 0, 5),
  [206] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_import_block_repeat1, 2, 0, 5), SHIFT_REPEAT(52),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [213] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [217] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [223] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [226] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_declaration, 2, 0, 9),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [237] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_value_property, 3, 0, 8),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_import_block_repeat1, 1, 0, 3),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_declaration, 3, 0, 11),
  [249] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_http_method, 1, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [253] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_go_zero_api(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "go_zero_api",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
